### ISSUE TITLE
DASH-IP-CHECK failed: org.gitlab4j.api.GitLabApiException: invalid_token 

### ISSUE THREAD

**Issue by stbischof** [eclipse-daanse/.eclipsefdn#25]
### Current Behavior
[netomi](https://github.com/netomi)

In CI we have a token to hande DASH-IP-CHECK

https://github.com/eclipse-daanse/.eclipsefdn/blob/6f9c7e03d6fd928895baa576f36dd72cee4bf1a1/otterdog/eclipse-daanse.jsonnet#L35C1-L37C73

the token seems to be timed out

https://github.com/eclipse-daanse/org.eclipse.daanse.jdbc.datasource/actions/runs/10907700765/job/30271988788#step:4:1182

### Expected Behavior

CI opens ip-dash issues

### Steps To Reproduce

see ci

### Version

current

### Are you interested in contributing a solution yourself?

No

**Comment by netomi** [comment]
@heurtematte could you regenerate the token please and provision it to GitHub?

@stbischof btw. I have provided an update to the mavenLicenseCheck workflow from the dash project with some advanced features like adding comments to the PR about the dependencies that are not vetted yet, you can find the PR here https://github.com/eclipse-dash/dash-licenses/pull/372

Maybe its useful also for your project, an example execution can be seen in these PRs

- https://github.com/OtterdogTest/macos-notarization-service/pull/6
- https://github.com/OtterdogTest/macos-notarization-service/pull/4

**Comment by stbischof** [comment]
Great. The main issue is that we get this only from internal pr?

Would be nice if it also could act on external pr.

**Comment by stbischof** [comment]
Sounds great! Will try soon

**Comment by heurtematte** [comment]
GitLab Api tokens were all renewed last week due to token expiration policy after a year introduce by GitLab.
So that a new script run every year renewing GitLab token for all eclipse projects, and for that purpose a token pattern has been used to refresh automatically token in all Eclipse GitHub Organization. 

This is the goal of this PR: https://github.com/eclipse-daanse/.eclipsefdn/pull/26

Unfortunately, this has a significant impact on all Daanse GitHub Project, according to this search: https://github.com/search?q=org%3Aeclipse-daanse%20DASH_IPLAB_TOKEN&type=code

Can you please migrate all those workflows referencing the new token naming convention `GITLAB_API_TOKEN`?

Apologize for the inconvenience.

**Comment by stbischof** [comment]
Sure i can

**Comment by netomi** [comment]
the token has been refreshed, the action is working again.

We can close this ticket now, see the open PR to adapt the workflows wrt new secret name.
If you are ready to go we can merge and apply this PR.
